In [1]:
from numpy import *

In [2]:
a=array([1,2,3,3,4])

In [3]:
a

array([1, 2, 3, 3, 4])

In [4]:
np.asarray(a)

NameError: name 'np' is not defined

In [ ]:
zeros(5)

In [ ]:
zeros((3,3,2))

In [ ]:
 5+zeros((3,4))

In [ ]:
empty((4,5))

In [ ]:
linspace(2,6)

In [5]:
a=linspace(2,6,10)

In [6]:
a.reshape(2,5)

array([[2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778],
       [4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]])

In [7]:
linspace(1,12,10,endpoint=False,retstep=True)

(array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9]), 1.1)

In [8]:
logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [9]:
a=arange(16)

In [10]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
a.max()

15

In [12]:
a=arange(2,30)

In [17]:
a.reshape(4,-1)

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29]])

In [14]:
a.max()

29

In [15]:
a.max(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [28]:
a.reshape(7,2,2)

array([[[ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21]],

       [[22, 23],
        [24, 25]],

       [[26, 27],
        [28, 29]]])

In [29]:
a.reshape(7,2,2).max(axis=1)

array([[ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21],
       [24, 25],
       [28, 29]])

In [30]:
a.reshape(7,2,2).max(axis=0)

array([[26, 27],
       [28, 29]])

In [35]:
arr=random.rand(1,36).reshape(6,6)

In [37]:
arr.reshape(6,6)

array([[0.69967616, 0.3949659 , 0.29032432, 0.28636484, 0.40142395,
        0.78174682],
       [0.90015129, 0.14273908, 0.69063313, 0.52199187, 0.55600725,
        0.05886817],
       [0.38059496, 0.62047613, 0.68586475, 0.54019491, 0.14718624,
        0.30203004],
       [0.08184664, 0.35921081, 0.76114165, 0.84739374, 0.53270417,
        0.49581098],
       [0.5836322 , 0.41829012, 0.84360074, 0.07429634, 0.15769469,
        0.69002387],
       [0.86335639, 0.30864967, 0.97968241, 0.54281213, 0.05053209,
        0.00383565]])

In [45]:
arr= linspace(1,100,36).reshape(6,6)

In [46]:
arr

array([[  1.        ,   3.82857143,   6.65714286,   9.48571429,
         12.31428571,  15.14285714],
       [ 17.97142857,  20.8       ,  23.62857143,  26.45714286,
         29.28571429,  32.11428571],
       [ 34.94285714,  37.77142857,  40.6       ,  43.42857143,
         46.25714286,  49.08571429],
       [ 51.91428571,  54.74285714,  57.57142857,  60.4       ,
         63.22857143,  66.05714286],
       [ 68.88571429,  71.71428571,  74.54285714,  77.37142857,
         80.2       ,  83.02857143],
       [ 85.85714286,  88.68571429,  91.51428571,  94.34285714,
         97.17142857, 100.        ]])

In [47]:
arr.max()

100.0

In [48]:
arr.max(axis=1)

array([ 15.14285714,  32.11428571,  49.08571429,  66.05714286,
        83.02857143, 100.        ])

In [49]:
arr=arange(4,40).reshape(6,6)

In [50]:
arr

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [52]:
arr.max()

39

In [53]:
arr.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [54]:
arr.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [57]:
arr[1:4,1:4]

array([[11, 12, 13],
       [17, 18, 19],
       [23, 24, 25]])

In [59]:
arr+10

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [60]:
arr/0

C:\Users\MSI\AppData\Local\Temp/ipykernel_2960/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [61]:
arr**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [69]:
b=array([2,2,3,4,5,6])

In [70]:
arr+b

array([[ 6,  7,  9, 11, 13, 15],
       [12, 13, 15, 17, 19, 21],
       [18, 19, 21, 23, 25, 27],
       [24, 25, 27, 29, 31, 33],
       [30, 31, 33, 35, 37, 39],
       [36, 37, 39, 41, 43, 45]])

In [71]:
arr+b.T

array([[ 6,  7,  9, 11, 13, 15],
       [12, 13, 15, 17, 19, 21],
       [18, 19, 21, 23, 25, 27],
       [24, 25, 27, 29, 31, 33],
       [30, 31, 33, 35, 37, 39],
       [36, 37, 39, 41, 43, 45]])

In [73]:
b.T
#can't be transposed

array([2, 2, 3, 4, 5, 6])

In [74]:
b=b.reshape(1,-1)

In [76]:
b

array([[2, 2, 3, 4, 5, 6]])

In [75]:
arr+b.T

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23, 24],
       [26, 27, 28, 29, 30, 31],
       [33, 34, 35, 36, 37, 38],
       [40, 41, 42, 43, 44, 45]])

In [77]:
x=array([1,2,3])

In [79]:
y=x

In [80]:
z=copy(x)

In [81]:
x[0]=100

In [82]:
y

array([100,   2,   3])

In [83]:
z

array([1, 2, 3])

In [84]:
id(x)

1542866118768

In [85]:
id(y)

1542866118768

In [86]:
id(z)

1542887403120

In [87]:
id(x[0])

1542900937488

In [88]:
id(y[0])

1542900937840